<?php

/**
 * Implements hook_menu().
 */
function unitpay_menu() {
    $items['unitpay/callback'] = array(
            'title' => 'Callback for unitpay request',
            'page callback' => 'unitpay_callback',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
    );

    return $items;
}

function unitpay_settings_form($settings = NULL) {
    $form = array();

    $settings = (array) $settings + array(
        'domain'     => '',
        'public_key' => '',
        'secret_key' => '',
    );

    $form['domain'] = array(
        '#type' => 'textfield',
        '#title' => t('DOMAIN'),
        '#description' => t('Вставьте ваш рабочий домен UnitPay'),
        '#default_value' =>  $settings['domain'],
    );

    $form['public_key'] = array(
        '#type' => 'textfield',
        '#title' => t('PUBLIC KEY'),
        '#description' => t('Скопируйте PUBLIC KEY со страницы проекта в системе Unitpay'),
        '#default_value' =>  $settings['public_key'],
    );

    $form['secret_key'] = array(
        '#type' => 'textfield',
        '#title' => t('SECRET KEY'),
        '#description' => t('Скопируйте SECRET KEY со страницы проекта в системе Unitpay'),
        '#default_value' => $settings['secret_key'],
    );

    $form['#submit'][] = variable_set('unitpay_settings', $form);

    return $form;
}

function unitpay_commerce_payment_method_info() {
    return array(
        'unitpay' => array(
            'title' => t('Unitpay'),
            'description' => t('Метод оплаты Unitpay'),
            'terminal' => FALSE,
            'offsite' => TRUE,
            'offsite_autoredirect' => TRUE,
            'active' => TRUE,
        ),
    );
}

/**
 * создаем форму для редиректа на страницу оплаты
 */
function unitpay_redirect_form($form, &$form_state, $order, $payment_method) {
    return unitpay_build_redirect_form($form, $form_state, $order, $payment_method['settings']);
}

function unitpay_build_redirect_form($form, &$form_state, $order, $settings) {
    // Choose a server to redirect.
    $domain = unitpay_get_setting('domain');
    $secret_key = unitpay_get_setting('secret_key');
    $public_key = unitpay_get_setting('public_key');

    $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
    $currency = $order_wrapper->commerce_order_total->currency_code->value();

    $sum = $order_wrapper->commerce_order_total->amount->value();
    $sum = $sum/100;
    $sum = number_format($sum, 2, '.','');


    $account = $order->order_id;
    $desc = 'Оплата по заказу №' . $order->order_number;

    $signature = hash('sha256', join('{up}', array(
            $order->order_id,
            $currency,
            $desc,
            $sum ,
            $secret_key
    )));

    $form['#action'] = "https://$domain/pay/" . $public_key;
    $form['sum'] = array(
        '#type' => 'hidden',
        '#value' => $sum,
    );
    $form['account'] = array(
        '#type' => 'hidden',
        '#value' => $account,
    );
    $form['desc'] = array(
        '#type' => 'hidden',
        '#value' => $desc,
    );
    $form['desc'] = array(
        '#type' => 'hidden',
        '#value' => $desc,
    );
    $form['currency'] = array(
        '#type' => 'hidden',
        '#value' => $currency,
    );

    $form['signature'] = array(
        '#type' => 'hidden',
        '#value' => $signature,
    );

    $has_email = $order->mail && (strlen($order->mail) > 0);


    if ($has_email) {
        $form['customerEmail'] = array(
            '#type' => 'hidden',
            '#value' => $order->mail,
        );
    }

    if($has_email){
        $form['cashItems'] = array(
            '#type' => 'hidden',
            '#value' => get_cash_items($order),
        );
    }

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Pay via Unitpay'),
    );

    return $form;
}

function get_cash_items($order)
{
    if (!$order) return '';

    $orderProducts = array();

    foreach(entity_metadata_wrapper('commerce_order', $order)->commerce_line_items as $item) {
        if (in_array($item->type->value(), commerce_product_line_item_types())) {
            $priceData = $item->commerce_unit_price->value();

            $orderProducts[] = array(
                'name'     => $item->commerce_product->title->value(),
                'count'    => number_format($item->quantity->value()),
                'price'    => number_format($priceData["amount"]/100, 2, '.', ''),
                'currency' => $priceData["currency_code"],
                'type'     => 'commodity',
                'nds'      => isset($priceData["data"]["include_tax"]) ? getTaxRates(preg_replace('/\D/', '', $priceData["data"]["include_tax"])) : 'none',
            );
        }
    }

    return base64_encode(json_encode($orderProducts));
}

function getTaxRates($rate){
    switch (intval($rate)){
        case 10:
            $vat = 'vat10';
            break;
        case 20:
            $vat = 'vat20';
            break;
        case 0:
            $vat = 'vat0';
            break;
        default:
            $vat = 'none';
    }

    return $vat;
}

/**
 * Page callback to receive payment notification from Unitpay.
 */
function unitpay_callback() {

    header('Content-type:application/json;  charset=utf-8');

    $method = '';
    $params = [];

    if ((isset($_GET['params'])) && (isset($_GET['method'])) && (isset($_GET['params']['signature']))){
        $params = $_GET['params'];
        $method = $_GET['method'];
        $signature = $params['signature'];

        if (empty($signature)){
            $status_sign = false;
        }else{
            $secret_key = unitpay_get_setting('secret_key');
            $status_sign = unitpay_verifySignature($params, $method, $secret_key);
        }
    }else{
        $status_sign = false;
    }

//    $status_sign = true;

    if ($status_sign){
        switch ($method) {
            case 'check':
                $result = unitpay_check( $params );
                break;
            case 'pay':
                $result = unitpay_payment( $params );
                break;
            case 'error':
                $result = unitpay_error( $params );
                break;
            default:
                $result = array('error' =>
                    array('message' => 'неверный метод')
                );
                break;
        }
    }else{
        $result = array('error' =>
            array('message' => 'неверная сигнатура')
        );
    }

    echo json_encode($result);
    die();
}


function unitpay_verifySignature($params, $method, $secret)
{
    return $params['signature'] == unitpay_getSignature($method, $params, $secret);
}
function unitpay_getSignature($method, array $params, $secretKey)
{
    ksort($params);
    unset($params['sign']);
    unset($params['signature']);
    array_push($params, $secretKey);
    array_unshift($params, $method);
    return hash('sha256', join('{up}', $params));
}
function unitpay_check( $params )
{
    $order = commerce_order_load($params['account']);

    if (!$order){
        $result = array('error' =>
                array('message' => 'заказа не существует')
        );
    }else{
        $wrapper = entity_metadata_wrapper('commerce_order', $order);
        $currency = $wrapper->commerce_order_total->currency_code->value();
        $sum = $wrapper->commerce_order_total->amount->value();
        $sum = $sum/100;
        $sum = number_format($sum, 2, '.','');

        if ((float)$sum != (float)$params['orderSum']) {
            $result = array('error' =>
                array('message' => 'не совпадает сумма заказа')
            );
        }elseif ($currency != $params['orderCurrency']) {
            $result = array('error' =>
                array('message' => 'не совпадает валюта заказа')
            );
        }
        else{
            $result = array('result' =>
                array('message' => 'Запрос успешно обработан')
            );
        }
    }

    return $result;
}

function unitpay_payment( $params )
{

    $order = commerce_order_load($params['account']);

    if (!$order){
        $result = array('error' =>
                array('message' => 'заказа не существует')
        );
    }else{
        $wrapper = entity_metadata_wrapper('commerce_order', $order);
        $currency = $wrapper->commerce_order_total->currency_code->value();
        $sum = $wrapper->commerce_order_total->amount->value();
        $sum = $sum/100;
        $sum = number_format($sum, 2, '.','');

        if ((float)$sum != (float)$params['orderSum']) {
            $result = array('error' =>
                array('message' => 'не совпадает сумма заказа')
            );
        }elseif ($currency != $params['orderCurrency']) {
            $result = array('error' =>
                array('message' => 'не совпадает валюта заказа')
            );
        }
        else{

            commerce_order_status_update($order, 'checkout_complete');
            commerce_order_status_update($order, 'completed_completed');
            commerce_order_status_update($order, 'completed');
            $result = array('result' =>
                array('message' => 'Запрос успешно обработан')
            );
        }
    }

    return $result;
}

function unitpay_error( $params )
{
    $order = commerce_order_load($params['account']);

    if (!$order){
        $result = array('error' =>
            array('message' => 'заказа не существует')
        );
    }
    else{
        commerce_order_status_update($order, 'canceled');
        $result = array('result' =>
            array('message' => 'Запрос успешно обработан')
        );
    }
    return $result;
}

function unitpay_get_setting($settings) {
    $output = '';
    $vars = variable_get('unitpay_settings', '');
    if (!empty($vars)) {
        foreach ($vars as $key=>$var) {
            if ($key == $settings) {
                $output = $vars[$key]['#default_value'];
                break;
            }
        }
    }
    return $output;
}